apiVersion: v1
kind: Service
metadata :
  name: monalisa-service-nginx
  labels:
    app: pro
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 31333
    port: 8000
    targetPort: 80
    protocol: "TCP"
  selector:
    app: pro
