apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine1
spec:
  selector:
    matchLabels:
      os: alpine
  replicas: 2
  template:
    metadata:
      labels:
        os: alpine
    spec:
      containers:
      - name: alpine1
        image: docker.io/shivaagn/angular-app
        command: ["/bin/sh","-c","sleep 60m"]
